"""add research_triggers table

Revision ID: 2f62d5f28a56
Revises: 77706c1b7ab2
Create Date: 2026-07-06 09:05:15.749972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f62d5f28a56'
down_revision: Union[str, Sequence[str], None] = '77706c1b7ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_triggers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_triggers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('source_alpha_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_hypothesis_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_hypothesis_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scenario_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('scenario_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('hypothesis_angle', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('scenario_constraint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('triggered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('consumed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('generated_hypothesis_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('research_triggers_pkey'))
    )
    # ### end Alembic commands ###
