"""baseline: full V2 schema

Revision ID: 77706c1b7ab2
Revises: 
Create Date: 2026-07-04 20:15:56.679549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77706c1b7ab2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_reports', 'alpha_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('learning_reports', 'simulation_start',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('learning_reports', 'simulation_end',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_reports', 'simulation_end',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('learning_reports', 'simulation_start',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('learning_reports', 'alpha_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
