import pandas as pd
from pathlib import Path


class LiveAllocationEngine:

    def __init__(self):

        self.optimization_path = Path("data/optimization")
        self.regime_path = Path("data/regimes")
        self.output_path = Path("results/reports")

    def load_inputs(self):

        weights = pd.read_csv(
            self.optimization_path / "probabilistic_regime_weights.csv"
        )

        forecast = pd.read_csv(
            self.regime_path / "next_regime_forecast.csv"
        )

        return weights, forecast

    def build_recommendation(self, weights, forecast):

        current_regime = forecast["current_regime"].iloc[0]

        top_next_regime = (
            forecast.sort_values(
                "probability",
                ascending=False
            )
            .iloc[0]["next_regime"]
        )

        top_probability = (
            forecast.sort_values(
                "probability",
                ascending=False
            )
            .iloc[0]["probability"]
        )

        weights_sorted = weights.sort_values(
            "weight",
            ascending=False
        )

        defensive_weight = weights[
            weights["asset"].isin(["TLT", "GLD", "VIX"])
        ]["weight"].sum()

        growth_weight = weights[
            weights["asset"].isin(["SPY", "QQQ", "DIA", "BTC-USD", "ETH-USD"])
        ]["weight"].sum()

        report = f"""
LIVE ALLOCATION RECOMMENDATION
==============================

Current Market Regime:
{current_regime}

Most Likely Next Regime:
{top_next_regime} ({top_probability:.2%} probability)

Recommended Probabilistic Allocation:
{weights_sorted.to_string(index=False)}

Allocation Summary:
- Growth / Risk Asset Weight: {growth_weight:.2%}
- Defensive / Hedge Asset Weight: {defensive_weight:.2%}

Interpretation:
The allocation is generated by blending regime-specific optimized portfolios using the estimated next-regime transition probabilities. This avoids hard switching between regimes and instead produces a smoother probabilistic allocation.

The current recommendation remains moderately growth-oriented because the most likely next regime is normal. However, the portfolio retains defensive exposure through TLT, GLD, and VIX to account for residual crisis probability.
"""

        return report

    def save_report(self, report):

        self.output_path.mkdir(
            parents=True,
            exist_ok=True
        )

        output_file = (
            self.output_path /
            "live_allocation_recommendation.txt"
        )

        with open(output_file, "w") as file:
            file.write(report)

        print(report)

        print(f"\nSaved recommendation: {output_file}")

    def run(self):

        print("=" * 60)
        print("LIVE ALLOCATION ENGINE")
        print("=" * 60)

        weights, forecast = self.load_inputs()

        report = self.build_recommendation(
            weights,
            forecast
        )

        self.save_report(report)


if __name__ == "__main__":

    engine = LiveAllocationEngine()

    engine.run()
