from pathlib import Path
import hashlib,json
ROOT=Path(__file__).resolve().parents[1]
FILES=[
 'src/optimization/signature_algorithm.py','src/institutional/mars_cvar_decision_bridge.py',
 'src/institutional/mars_cvar_product.py','src/institutional/enterprise_readiness.py','src/institutional/deployment_preflight.py','src/institutional/ai_intelligence.py','src/institutional/live_data_contract.py','src/institutional/live_data_ingestion.py','src/institutional/public_data.py','src/institutional/model_validation.py','src/institutional/enterprise_platform.py','src/institutional/ai_evaluation.py','src/institutional/control_plane.py','src/institutional/operations_contract.py','src/institutional/external_evidence.py','src/institutional/synthetic_ml.py','src/institutional/research_operations.py','scripts/product_adapter.py','scripts/product_runtime.py','scripts/product_frontend.py','scripts/ingest_public_data.py','scripts/run_deployment_preflight.py','scripts/generate_synthetic_ml_dataset.py','scripts/run_synthetic_ml_validation.py','scripts/verify_enterprise_release.py','scripts/export_enterprise_evidence.py','scripts/generate_sbom.py',
 'src/api/main.py','src/institutional/mars_cvar_reference.py','scripts/rc3_windows_acceptance.py','scripts/run_mars_cvar_institutional.py',
 'scripts/mars_cvar_governance_evidence.py','scripts/mars_cvar_walk_forward_evidence.py',
 'results/institutional/mars_cvar_decision.json','tests/test_signature_algorithm.py','tests/test_mars_cvar_institutional_bridge.py',
 'tests/test_mars_cvar_product.py','tests/test_mars_cvar_validation.py','tests/test_mars_cvar_api_ui.py','tests/test_enterprise_readiness.py','tests/test_product_frontend.py','tests/test_research_operations.py','tests/test_ai_intelligence.py','tests/test_governed_controls.py','tests/test_external_evidence.py','tests/test_synthetic_ml.py','tests/test_public_data.py','tests/test_release_verifier.py','tests/test_evidence_bundle.py','tests/test_sbom.py','dashboard/official_dashboard.py',
 'src/institutional/mars_cvar_validation.py',
 'artifacts/mars_cvar/governance_evidence.json','artifacts/mars_cvar/turnover_sensitivity.csv','artifacts/mars_cvar/GOVERNANCE_REPORT.md','artifacts/compliance/deployment_preflight.json','artifacts/compliance/live_data_status.json','artifacts/compliance/model_validation.json','artifacts/compliance/enterprise_platform.json','artifacts/compliance/ai_evaluation.json','artifacts/compliance/control_plane.json','artifacts/compliance/operations_status.json','artifacts/compliance/customer_evidence_status.json','artifacts/compliance/production_image_provenance_status.json','artifacts/product_runtime/latest_ai_intelligence_brief.json','artifacts/research_operations/latest_research_operations.json','artifacts/synthetic/synthetic_ml_dataset.csv','artifacts/synthetic/synthetic_ml_dataset_manifest.json','artifacts/synthetic/synthetic_ml_validation.json',
 'docs/SIGNATURE_ALGORITHM.md','docs/RESEARCH_VALIDATION_MARS_CVAR.md','docs/RESEARCH_OPERATIONS.md','docs/PRODUCT_RUNTIME.md','docs/ENTERPRISE_OPERATING_MODEL.md','docs/OPERATIONS_RUNBOOK.md','docs/DISASTER_RECOVERY.md','docs/AI_INTELLIGENCE.md','docs/LIVE_DATA_AND_VALIDATION.md','docs/ENTERPRISE_CUSTOMER_READINESS.md',
 'docker-compose.yml','docker-compose.production.yml','Dockerfile.api','Dockerfile.dashboard','configs/prod.yaml','config/ai_settings.json','config/operations.json','config/customer_evidence.example.json','config/production_image_provenance.example.json',
 'schemas/aurum_readiness.schema.json','schemas/aurum_role_policy.schema.json','schemas/aurum_evidence_bundle.schema.json','schemas/aurum_sbom.schema.json','schemas/aurum_deployment_preflight.schema.json','schemas/aurum_live_data.schema.json','schemas/aurum_control_plane.schema.json','schemas/aurum_operations.schema.json','schemas/aurum_customer_evidence.schema.json','schemas/aurum_production_image_provenance.schema.json','schemas/aurum_synthetic_dataset_manifest.schema.json','schemas/aurum_synthetic_ml_validation.schema.json','schemas/aurum_public_data_manifest.schema.json','artifacts/compliance/sbom.json','artifacts/public_data/public_data_manifest.json','artifacts/public_data/sec_companyfacts_CIK0000789019.json','artifacts/public_data/sec_companyfacts_CIK0000019617.json','artifacts/public_data/sec_companyfacts_CIK0000070858.json','artifacts/public_data/fdic_institutions.json','artifacts/public_data/treasury_debt_to_penny.json','artifacts/public_data/market_prices.csv','artifacts/public_data/public_market_validation.json']

def main():
    missing=[f for f in FILES if not (ROOT/f).exists()]
    if missing: raise SystemExit('missing: '+','.join(missing))
    manifest={"algorithm":"MARS-CVaR","files":{}}
    for f in FILES:
        b=(ROOT/f).read_bytes(); manifest['files'][f]={"sha256":hashlib.sha256(b).hexdigest(),"bytes":len(b)}
    out=ROOT/'artifacts/mars_cvar/release_manifest.json'; out.parent.mkdir(parents=True,exist_ok=True); out.write_text(json.dumps(manifest,indent=2),encoding='utf-8')
    print(f"MARS_CVAR_RELEASE_EVIDENCE={len(FILES)}/{len(FILES)}")
if __name__=='__main__': main()
