import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

import streamlit as st
import pandas as pd
import json
from src.core.database import SessionLocal
from src.models.hypothesis import Hypothesis
from src.models.governance import GovernanceRecord
from src.models.research_memory import ResearchMemory
from src.models.alpha_registry import AlphaSignal
from sqlalchemy import text

st.set_page_config(page_title="AURUM V2 — Research Terminal", layout="wide")

def get_db():
    return SessionLocal()

def load_hypotheses(db):
    rows = db.query(Hypothesis).order_by(Hypothesis.hypothesis_number).all()
    data = []
    for h in rows:
        gov = db.query(GovernanceRecord).filter_by(hypothesis_id=h.id).first()
        data.append({
            "#": h.hypothesis_number,
            "Title": h.title,
            "Status": h.status.value if h.status else None,
            "Stage": gov.current_stage.value if gov else None,
            "Sharpe": h.sharpe_ratio,
            "Sortino": h.sortino_ratio,
            "Max DD": h.max_drawdown,
            "Ann. Return": h.annualized_return,
            "Win Rate": h.win_rate,
            "Holding (d)": h.expected_holding_days,
            "Has Debate": bool(gov and gov.debate_record),
        })
    return pd.DataFrame(data)

def load_memories(db):
    rows = db.query(ResearchMemory).order_by(ResearchMemory.created_at).all()
    return rows

# ── Sidebar navigation ────────────────────────────────────────────
st.sidebar.title("AURUM V2")
st.sidebar.caption("AI-native quantitative research firm")
st.sidebar.markdown("**Research Operations**")
page = st.sidebar.radio("Navigate", [
    "🏠 Mission Control",
    "📋 Experiment Board",
    "⏳ Approval Queue",
    "📈 Paper Trading Queue",
    "🗄️ Retirement Queue",
    "──────────────",
    "Research Feed",
    "Hypothesis Detail",
    "Research Memory",
    "Memory Lineage",
    "Alpha Registry",
    "Research Copilot",
    "Knowledge Graph",
    "Macro Data",
    "Portfolio Lab"
])

db = get_db()

# ── Page: Research Feed ───────────────────────────────────────────
if page == "Research Feed":
    st.title("Research feed")
    st.caption("Every hypothesis generated by the Research Scientist, with current governance stage and validated performance.")

    df = load_hypotheses(db)

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total hypotheses", len(df))
    col2.metric("In paper trading", (df["Stage"] == "paper_trading").sum())
    col3.metric("Debated", df["Has Debate"].sum())
    col4.metric("Avg Sharpe (validated)", round(df["Sharpe"].dropna().mean(), 2) if df["Sharpe"].notna().any() else "—")

    st.divider()

    display_df = df.drop(columns=["Has Debate"]).copy()
    for col in ["Sharpe", "Sortino", "Max DD", "Ann. Return", "Win Rate"]:
        display_df[col] = display_df[col].apply(lambda x: f"{x:.3f}" if pd.notna(x) else "—")

    st.dataframe(display_df, use_container_width=True, hide_index=True)

    st.divider()
    st.markdown("### Pending actions")
    st.caption("Hypotheses waiting for a governance decision.")

    pending_stages = ["idea", "experiment", "statistical_review", "risk_review", "committee"]
    pending = df[df["Stage"].isin(pending_stages) & (df["Status"] != "failed")]

    if pending.empty:
        st.info("Nothing pending — all active hypotheses are either in paper trading, production, or retired.")
    else:
        for _, row in pending.iterrows():
            with st.container(border=True):
                c1, c2, c3 = st.columns([3, 1, 1])
                c1.markdown(f"**#{row['#']} — {row['Title']}**")
                c2.markdown(f"`{row['Stage']}`")
                c3.markdown(f"Sharpe: {row['Sharpe']}")

# ── Page: Hypothesis Detail ───────────────────────────────────────
elif page == "Hypothesis Detail":
    st.title("Hypothesis detail")

    df = load_hypotheses(db)
    hyp_number = st.selectbox("Select hypothesis", df["#"].tolist())

    hyp = db.query(Hypothesis).filter_by(hypothesis_number=hyp_number).first()
    gov = db.query(GovernanceRecord).filter_by(hypothesis_id=hyp.id).first()

    st.subheader(f"#{hyp.hypothesis_number} — {hyp.title}")
    
    # Show persistent action feedback across reruns
    action_key = f"last_action_{hyp.hypothesis_number}"
    if action_key in st.session_state:
        msg = st.session_state[action_key]
        if msg.startswith("✅"):
            st.success(msg)
        else:
            st.error(msg)
        del st.session_state[action_key]
    
    st.write(hyp.thesis)

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Sharpe", f"{hyp.sharpe_ratio:.3f}" if hyp.sharpe_ratio else "—")
    c2.metric("Sortino", f"{hyp.sortino_ratio:.3f}" if hyp.sortino_ratio else "—")
    c3.metric("Max DD", f"{hyp.max_drawdown:.1%}" if hyp.max_drawdown else "—")
    c4.metric("Ann. Return", f"{hyp.annualized_return:.1%}" if hyp.annualized_return else "—")
    c5.metric("Win Rate", f"{hyp.win_rate:.1%}" if hyp.win_rate else "—")

    st.divider()

    tab1, tab2, tab3, tab4 = st.tabs(["Signal components", "Governance timeline", "Committee debate", "Raw JSON"])

    with tab1:
        st.json(hyp.signal_components)
        st.caption(f"Conditions: {json.dumps(hyp.conditions)}")
        st.caption(f"Universe: {hyp.universe} | Holding period: {hyp.expected_holding_days} days")

    with tab2:
        if gov and gov.stage_history:
            for entry in gov.stage_history:
                with st.container(border=True):
                    st.markdown(f"**{entry.get('to_stage', 'unknown')}** — {entry.get('timestamp', '')[:19]}")
                    st.caption(entry.get("notes", ""))
        else:
            st.info("No governance history available.")

        st.divider()
        st.markdown("### Governance actions")

        from src.agents.governance_actions import get_allowed_actions, advance_stage, retire_hypothesis
        from src.models.governance import GovernanceStage

        # Re-fetch gov after any potential rerun to get fresh stage
        gov = db.query(GovernanceRecord).filter_by(hypothesis_id=hyp.id).first()
        actions = get_allowed_actions(hyp, gov)

        if not actions:
            st.info("No actions available from current stage.")
        else:
            notes_key = f"notes_{hyp.hypothesis_number}"
            notes_input = st.text_input(
                "Notes (optional)", key=notes_key,
                placeholder="Reason for this transition..."
            )

            # Handle pending action from previous render cycle
            pending_key = f"pending_action_{hyp.hypothesis_number}"
            if pending_key in st.session_state:
                pending = st.session_state.pop(pending_key)
                target = GovernanceStage(pending["target"])
                notes = pending["notes"]

                if target == GovernanceStage.RETIRED:
                    if not notes:
                        st.error("Retirement reason is required.")
                    else:
                        ok, msg = retire_hypothesis(db, hyp, notes)
                        if ok:
                            st.success(f"✅ {msg}")
                            st.rerun()
                        else:
                            st.error(f"❌ {msg}")
                else:
                    ok, msg = advance_stage(db, hyp, target, notes)
                    if ok:
                        st.success(f"✅ {msg}")
                        st.rerun()
                    else:
                        st.error(f"❌ {msg}")

            # Render action buttons
            for action in actions:
                col_btn, col_reason = st.columns([1, 3])
                btn_key = f"btn_{hyp.hypothesis_number}_{action['target_stage'].value}"

                with col_btn:
                    if action["target_stage"] == GovernanceStage.RETIRED:
                        clicked = st.button(
                            f"🗄️ {action['label']}", key=btn_key,
                            disabled=not action["enabled"], type="secondary"
                        )
                    else:
                        clicked = st.button(
                            f"→ {action['label']}", key=btn_key,
                            disabled=not action["enabled"], type="primary"
                        )

                with col_reason:
                    if not action["enabled"]:
                        st.caption(f"⛔ {action['blocked_reason']}")
                    else:
                        st.caption("✅ Prerequisites met")

                if clicked:
                    st.session_state[pending_key] = {
                        "target": action["target_stage"].value,
                        "notes": notes_input
                    }
                    st.rerun()

    with tab3:
        if gov and gov.debate_record:
            d = gov.debate_record
            colA, colB = st.columns(2)

            with colA:
                st.markdown("### 🐂 Bull case")
                for p in d["bull"]["thesis_points"]:
                    st.markdown(f"- {p}")
                st.success(f"**Strongest argument:** {d['bull']['strongest_argument']}")
                st.caption(f"Confidence: {d['bull']['confidence']}")

            with colB:
                st.markdown("### 🐻 Bear case")
                for p in d["bear"]["rebuttal_points"]:
                    st.markdown(f"- {p}")
                st.error(f"**Strongest objection:** {d['bear']['strongest_objection']}")
                st.caption(f"Confidence: {d['bear']['confidence']}")

            st.divider()
            st.markdown("### ⚖️ Risk assessment")
            for f in d["risk"]["risk_flags"]:
                st.markdown(f"- {f}")
            r1, r2, r3 = st.columns(3)
            r1.metric("Concentration risk", d["risk"]["concentration_risk"])
            r2.metric("Overall rating", d["risk"]["overall_risk_rating"])
            r3.metric("Position limit", d["risk"]["recommended_position_limit"][:30])

            st.divider()
            st.markdown("### 🏛️ Committee decision")
            j = d["judge"]
            decision_color = {"approve_paper_trading": "success", "reject": "error", "request_revision": "warning"}
            getattr(st, decision_color.get(j["decision"], "info"))(f"**{j['decision'].upper()}**")
            st.write(j["justification"])
            st.caption(f"Addressed bear objection: {j['addressed_bear_objection']}")
            if j.get("conditions_for_approval"):
                st.markdown("**Conditions:**")
                for c in j["conditions_for_approval"]:
                    st.markdown(f"- {c}")
        else:
            st.info("This hypothesis has not been through committee debate yet.")

    with tab4:
        st.json({
            "hypothesis": hyp.signal_components,
            "governance_stage": gov.current_stage.value if gov else None,
            "committee_decision": gov.committee_decision if gov else None,
        })

# ── Page: Research Memory ─────────────────────────────────────────
elif page == "Research Memory":
    st.title("Research memory")
    st.caption("Lessons extracted from failed or flawed research, consulted automatically before new hypothesis generation.")

    memories = load_memories(db)

    if not memories:
        st.info("No research memories yet.")
    else:
        st.metric("Total memories", len(memories))
        st.divider()

        for m in memories:
            with st.container(border=True):
                col1, col2 = st.columns([3, 1])
                with col1:
                    st.markdown(f"**{m.failure_mode}**")
                    st.caption(f"From Hypothesis #{m.source_hypothesis_number} · {m.created_by}")
                with col2:
                    st.caption(f"Affects: {', '.join(m.affected_signal_types)}")

                st.write(m.lesson)

                with st.expander("Structured constraint"):
                    st.json(m.structured_constraint)

# ── Page: Memory Lineage ──────────────────────────────────────────
elif page == "Memory Lineage":
    st.title("Memory lineage")
    st.caption("The self-correcting research loop: a debate finds a flaw, a memory captures it, a future hypothesis adapts to it.")

    memories = load_memories(db)
    hyp_lookup = {h.hypothesis_number: h for h in db.query(Hypothesis).all()}

    if not memories:
        st.info("No memories yet.")
    else:
        for m in memories:
            source_hyp = hyp_lookup.get(m.source_hypothesis_number)
            influenced = m.influenced_hypothesis_numbers or []

            with st.container(border=True):
                col1, col2, col3 = st.columns([1, 1, 1])

                with col1:
                    st.markdown("**Source hypothesis**")
                    if source_hyp:
                        st.markdown(f"#{source_hyp.hypothesis_number} — {source_hyp.title}")
                        st.caption(f"Sharpe: {source_hyp.sharpe_ratio} · Max DD: {source_hyp.max_drawdown}")
                    else:
                        st.caption("Unknown source")

                with col2:
                    st.markdown("**→ Memory extracted →**")
                    st.markdown(f"`{m.failure_mode}`")
                    st.caption(m.lesson[:140] + "..." if len(m.lesson) > 140 else m.lesson)

                with col3:
                    st.markdown("**→ Influenced**")
                    if influenced:
                        for hyp_num in influenced:
                            target_hyp = hyp_lookup.get(hyp_num)
                            if target_hyp:
                                st.markdown(f"#{target_hyp.hypothesis_number} — {target_hyp.title}")
                                st.caption(f"Sharpe: {target_hyp.sharpe_ratio} · Max DD: {target_hyp.max_drawdown}")
                    else:
                        st.caption("Not yet applied to a new hypothesis")

        st.divider()
        st.markdown("### Full lineage chain")

        chain_md = """
H3 (no stat review, VIX gate flaw)
H4 (VIX gate flaw, selection bias)
        |
        v
   Memory: timing_mismatch
   Memory: selection_bias
        |
        v
H7 (10-day hold, fixed VIX=18 circuit breaker)
        |
        v
   Backtest reveals: 69.5% trigger rate, Sharpe 1.14 -> 0.31 with breaker on
        |
        v
   Memory: circuit_breaker_overcalibration
        |
        v
H8 (percentile-based dynamic threshold, 88th percentile VIX)
        |
        v
   Debate catches: circular calibration, no out-of-sample validation yet
        |
        v
   Paper trading mandated to validate before live deployment
"""
        st.code(chain_md, language=None)

        st.markdown("""
**The pattern**: every hypothesis after #4 exists because a debate or backtest found a specific,
named flaw in its predecessor. The system is not just generating ideas — it is generating ideas
that respond to its own documented failures, with the response itself then subjected to fresh
scrutiny by the committee.
""")

# ── Page: Alpha Registry ──────────────────────────────────────────
elif page == "Alpha Registry":
    st.title("Alpha registry")
    st.caption("Hypotheses that survived backtest, statistical validation, and committee debate — the system's actual research output.")

    alphas = db.query(AlphaSignal).order_by(AlphaSignal.registered_at).all()
    hyp_lookup = {h.id: h for h in db.query(Hypothesis).all()}

    if not alphas:
        st.info("No alphas registered yet.")
    else:
        c1, c2, c3 = st.columns(3)
        c1.metric("Registered alphas", len(alphas))
        c2.metric("Avg Sharpe", round(sum(a.sharpe_ratio for a in alphas) / len(alphas), 3))
        c3.metric("Active", sum(1 for a in alphas if a.is_active))

        st.divider()

        for a in alphas:
            hyp = hyp_lookup.get(a.hypothesis_id)
            with st.container(border=True):
                col1, col2 = st.columns([2, 1])

                with col1:
                    st.markdown(f"### {a.signal_name}")
                    if hyp:
                        st.caption(f"From Hypothesis #{hyp.hypothesis_number} · Universe: {a.universe} · "
                                   f"Registered {a.registered_at.strftime('%Y-%m-%d')}")

                with col2:
                    status = "🟢 Active" if a.is_active else "⚪ Inactive"
                    st.markdown(f"**{status}**")
                    if a.decay_flag:
                        st.warning("Decay flagged")
                    if a.retirement_recommended:
                        st.error("Retirement recommended")

                m1, m2, m3, m4, m5 = st.columns(5)
                m1.metric("Sharpe", f"{a.sharpe_ratio:.3f}")
                m2.metric("Sortino", f"{a.sortino_ratio:.3f}")
                m3.metric("Calmar", f"{a.calmar_ratio:.3f}")
                m4.metric("Max DD", f"{a.max_drawdown:.1%}")
                m5.metric("Win Rate", f"{a.win_rate:.1%}")

                if a.paper_trading_sharpe is not None:
                    st.caption(f"Paper trading Sharpe: {a.paper_trading_sharpe} "
                               f"(vs. backtest {a.sharpe_ratio})")

                with st.expander("Signal construction logic"):
                    st.code(a.signal_code, language="python")

                with st.expander("Features used"):
                    st.write(", ".join(a.features_used))

                # Latest learning report for this alpha
                latest = db.execute(text(
                    "SELECT paper_sharpe, paper_max_drawdown, paper_win_rate, "
                    "sharpe_degradation, vix_max_observed, vix_breach_occurred, "
                    "circuit_breaker_triggers, recommended_action, evaluated_at "
                    "FROM learning_reports WHERE hypothesis_id = :hid "
                    "ORDER BY evaluated_at DESC LIMIT 1"
                ), {"hid": str(a.hypothesis_id)}).fetchone()

                if latest:
                    with st.expander("Latest learning report"):
                        lr1, lr2, lr3 = st.columns(3)
                        lr1.metric("Paper Sharpe", f"{latest.paper_sharpe:.3f}",
                                   delta=f"{(latest.paper_sharpe - a.sharpe_ratio):.3f} vs backtest")
                        lr2.metric("Paper Max DD", f"{latest.paper_max_drawdown:.1%}")
                        lr3.metric("Recommendation", latest.recommended_action)
                        st.caption(f"Evaluated: {str(latest.evaluated_at)[:19]} | "
                                   f"VIX max: {latest.vix_max_observed} "
                                   f"({'breach' if latest.vix_breach_occurred else 'no breach'}) | "
                                   f"Circuit breaker fired: {latest.circuit_breaker_triggers}x")

# ── Page: Research Copilot ────────────────────────────────────────
elif page == "Research Copilot":
    st.title("Research copilot")
    st.caption("Ask anything about the hypothesis corpus, debate findings, research memories, or alpha registry.")

    from src.agents.research_copilot import query_copilot

    # Example questions
    examples = [
        "Which hypotheses failed because of regime conditioning?",
        "What did the Bear Agent find wrong with H#7?",
        "What lessons have we learned about VIX circuit-breakers?",
        "Which alphas are active and what are their paper trading results?",
        "What should we test next based on what we know?",
        "Which hypotheses have been through the full governance pipeline?",
    ]

    st.markdown("**Example questions** — click to run instantly:")
    cols = st.columns(3)
    for i, ex in enumerate(examples):
        if cols[i % 3].button(ex, key=f"ex_{i}", use_container_width=True):
            with st.spinner("Searching research corpus..."):
                answer = query_copilot(db, ex)
            st.session_state["copilot_answer"] = answer
            st.session_state["copilot_last_question"] = ex
            st.rerun()

    st.divider()

    question = st.text_input(
        "Or ask your own question",
        placeholder="e.g. Which strategies survived the VIX spike?",
        key="copilot_input"
    )

    if st.button("Ask", type="primary", key="copilot_ask") and question:
        with st.spinner("Searching research corpus..."):
            answer = query_copilot(db, question)
        st.session_state["copilot_answer"] = answer
        st.session_state["copilot_last_question"] = question

    if "copilot_answer" in st.session_state:
        st.divider()
        if "copilot_last_question" in st.session_state:
            st.caption(f"Q: {st.session_state['copilot_last_question']}")
        st.markdown("### Answer")
        st.markdown(st.session_state["copilot_answer"])
        if st.button("Clear", key="copilot_clear"):
            del st.session_state["copilot_answer"]
            del st.session_state["copilot_last_question"]

# ── Page: Knowledge Graph ─────────────────────────────────────────
elif page == "Knowledge Graph":
    st.title("Knowledge graph")
    st.caption("Entity relationships, sector peers, ETF exposure, and macro sensitivities — the semantic layer over market data.")

    from src.data.relational_knowledge_store import get_knowledge_store, ENTITY_DATA, ETF_CONSTITUENCIES
    import pandas as pd

    ks = get_knowledge_store()

    tab_sector, tab_etf, tab_entity, tab_crowding = st.tabs([
        "Sector map", "ETF constituencies", "Entity lookup", "Crowding analysis"
    ])

    with tab_sector:
        st.markdown("### Sector distribution across universe")
        sector_data = {}
        for ticker, data in ENTITY_DATA.items():
            sector = data[1]
            sector_data.setdefault(sector, []).append(ticker)

        for sector, tickers in sorted(sector_data.items(), key=lambda x: -len(x[1])):
            with st.container(border=True):
                c1, c2 = st.columns([1, 4])
                c1.metric(sector.split(" ")[-1], len(tickers))
                c2.write(", ".join(tickers))

    with tab_etf:
        st.markdown("### ETF constituency map")
        etf_rows = []
        for etf, tickers in ETF_CONSTITUENCIES.items():
            etf_rows.append({"ETF": etf, "Holdings": len(tickers), "Tickers": ", ".join(tickers[:8]) + ("..." if len(tickers) > 8 else "")})
        st.dataframe(pd.DataFrame(etf_rows), use_container_width=True, hide_index=True)

    with tab_entity:
        st.markdown("### Entity detail")
        ticker = st.selectbox("Select ticker", sorted(ENTITY_DATA.keys()))
        entity = ks.get_entity(ticker)
        if entity:
            c1, c2, c3 = st.columns(3)
            c1.metric("Sector", entity.sector.split(" ")[-1])
            c2.metric("Industry", entity.industry[:20])
            c3.metric("Cap tier", entity.market_cap_tier)

            st.markdown("**ETF memberships:**")
            etfs = ks.get_etf_exposure(ticker)
            if etfs:
                st.write(", ".join(e["etf"] for e in etfs))
            else:
                st.write("None in our tracked ETFs")

            st.markdown("**Macro sensitivities:**")
            macros = ks.get_macro_sensitivities(ticker)
            for m in macros:
                st.markdown(f"- `{m}`")

            st.markdown("**Sector peers:**")
            peers = ks.get_peers(ticker)
            st.write(", ".join(p.ticker for p in peers))

    with tab_crowding:
        st.markdown("### Portfolio crowding analysis")
        st.caption("Select tickers to see ETF overlap and sector concentration risk.")

        selected = st.multiselect(
            "Select tickers",
            sorted(ENTITY_DATA.keys()),
            default=["NVDA", "AMD", "META", "MSFT", "AAPL", "GOOGL", "AMZN"]
        )

        if selected:
            c1, c2 = st.columns(2)

            with c1:
                st.markdown("**Sector concentration:**")
                concentration = ks.get_sector_concentration(selected)
                for sector, info in concentration.items():
                    flag = "⚠️" if info["concentration_flag"] else "✅"
                    st.markdown(f"{flag} **{sector}**: {info['count']} tickers ({info['pct']*100:.0f}%)")

            with c2:
                st.markdown("**ETF crowding:**")
                crowding = ks.get_common_etf_exposure(selected)
                if crowding:
                    for etf, info in sorted(crowding.items(), key=lambda x: -x[1]["overlap_count"])[:8]:
                        risk_color = "🔴" if info["concentration_risk"] == "high" else "🟡" if info["concentration_risk"] == "medium" else "🟢"
                        st.markdown(f"{risk_color} **{etf}**: {info['overlap_count']}/{len(selected)} names")
                else:
                    st.info("No common ETF exposure found.")

# ── Page: Portfolio Lab ───────────────────────────────────────────
elif page == "Portfolio Lab":
    st.title("Portfolio laboratory")
    st.caption("Stress-test registered alphas against macro scenarios — decisions require approval before writing to governance.")

    from src.agents.mars_cvar_engine_bridge import load_mars_cvar_context
    mars_context = load_mars_cvar_context()
    with st.container(border=True):
        st.markdown("### Quantitative engine context — MARS-CVaR")
        if mars_context.get("available"):
            m1, m2, m3 = st.columns(3)
            m1.metric("Engine gate", mars_context.get("risk_gate", "UNKNOWN"))
            m2.metric("CVaR loss", f"{mars_context.get('cvar_loss', 0.0):.4f}")
            m3.metric("Turnover (L1)", f"{mars_context.get('turnover', 0.0):.3f}")
            st.caption(f"Decision {mars_context.get('decision_id')} · read-only research context")
            st.dataframe(pd.DataFrame([mars_context.get("target_weights", {})]), use_container_width=True, hide_index=True)
            st.warning(mars_context.get("usage_boundary"))
            st.caption(mars_context.get("claim_boundary"))
        else:
            st.info("MARS-CVaR engine artifact is not available. Portfolio Lab remains research-only.")

    from src.agents.portfolio_lab import SCENARIOS, estimate_alpha_scenario_impact, explain_scenario_impact
    from src.agents.scenario_decision_engine import make_scenario_decision, apply_scenario_decision
    from src.models.alpha_registry import AlphaSignal

    alphas = db.query(AlphaSignal).filter_by(is_active=True).all()

    if not alphas:
        st.info("No active alphas in the registry to stress-test.")
    else:
        col1, col2 = st.columns([1, 2])

        with col1:
            st.markdown("### Select scenario")
            scenario_key = st.radio(
                "Scenario",
                list(SCENARIOS.keys()),
                format_func=lambda k: SCENARIOS[k]["name"],
                key="lab_scenario"
            )
            scenario = SCENARIOS[scenario_key]
            st.divider()
            st.caption(scenario["description"])
            st.caption(f"Historical analogs: {', '.join(scenario['historical_analogs'])}")
            st.caption(f"VIX spike: +{scenario['vix_spike']} pts | "
                      f"Duration: {scenario['duration_days']}d")

        with col2:
            st.markdown("### Alpha impact + decisions")

            if st.button("Run stress test", type="primary", key="lab_run"):
                results = []
                with st.spinner(f"Analysing {len(alphas)} alpha(s)..."):
                    for alpha in alphas:
                        hyp = db.query(Hypothesis).filter_by(
                            id=alpha.hypothesis_id
                        ).first()
                        if not hyp:
                            continue
                        impact = estimate_alpha_scenario_impact(
                            alpha, hyp, scenario
                        )
                        explanation = explain_scenario_impact(
                            alpha, hyp, scenario_key, impact
                        )
                        decision = make_scenario_decision(
                            alpha, hyp, scenario_key,
                            scenario, impact, explanation
                        )
                        results.append({
                            "alpha": alpha,
                            "hyp": hyp,
                            "impact": impact,
                            "explanation": explanation,
                            "decision": decision,
                            "applied": False
                        })
                st.session_state["lab_results"] = results
                st.session_state["lab_scenario_key"] = scenario_key
                st.session_state["lab_scenario_name"] = scenario["name"]

            if "lab_results" in st.session_state:
                for i, r in enumerate(st.session_state["lab_results"]):
                    impact = r["impact"]
                    alpha = r["alpha"]
                    hyp = r["hyp"]
                    decision = r["decision"]

                    with st.container(border=True):
                        # Header row
                        h1, h2, h3, h4, h5 = st.columns([2, 1, 1, 1, 1])
                        h1.markdown(f"**H#{hyp.hypothesis_number}**")
                        impact_pct = impact['estimated_portfolio_impact'] * 100
                        h2.metric("Impact", f"{impact_pct:.1f}%",
                                 delta=f"{impact_pct:.1f}%",
                                 delta_color="inverse")
                        h3.metric("CB", "FIRES ✅" if impact[
                            "circuit_breaker_fires"] else "idle ⚠️")

                        # Decision badge
                        decision_action = decision.get("decision", "HOLD")
                        decision_colors = {
                            "HOLD": "🟢", "REDUCE": "🟡", "HEDGE": "🟡",
                            "RECALIBRATE": "🟠", "RETIRE": "🔴", "RESEARCH": "🔵"
                        }
                        h4.markdown(
                            f"**{decision_colors.get(decision_action, '⚪')} "
                            f"{decision_action}**"
                        )
                        h5.metric("Confidence",
                                 f"{decision.get('confidence', 0):.0%}")

                        st.caption(alpha.signal_name)

                        # Rationale
                        with st.expander("Decision rationale"):
                            st.write(decision.get("rationale", ""))
                            if decision.get("action_detail"):
                                st.info(f"**Recommended action:** "
                                       f"{decision['action_detail']}")
                            if decision_action == "RESEARCH" and decision.get(
                                    "research_trigger"):
                                rt = decision["research_trigger"]
                                st.success(
                                    f"**New research angle:** {rt.get('hypothesis_angle')}\n\n"
                                    f"**Scenario constraint:** {rt.get('scenario_constraint')}\n\n"
                                    f"**Priority:** {rt.get('priority', 'medium')}"
                                )

                        # Explanation
                        with st.expander("Scenario analysis"):
                            st.write(r["explanation"])

                        # Apply button (only if not already applied)
                        if not r.get("applied"):
                            if decision_action != "HOLD":
                                apply_key = f"apply_{i}_{hyp.hypothesis_number}"
                                if st.button(
                                    f"✅ Apply {decision_action} decision",
                                    key=apply_key,
                                    type="secondary"
                                ):
                                    applied = apply_scenario_decision(
                                        db, alpha, hyp, decision,
                                        st.session_state.get(
                                            "lab_scenario_key", scenario_key
                                        ),
                                        st.session_state.get(
                                            "lab_scenario_name", scenario["name"]
                                        )
                                    )
                                    st.session_state["lab_results"][i]["applied"] = True
                                    st.success(f"Applied: {applied['result']}")
                                    st.rerun()
                            else:
                                st.caption("✅ HOLD — no action required")
                        else:
                            st.caption("✅ Decision applied to governance")


# Handle divider
if page == "──────────────":
    st.info("Select a page from the navigation.")
elif page == "🏠 Mission Control":
    st.title("Mission control")
    st.caption("AURUM V2 research operations — what needs attention right now.")

    from src.agents.workflow_engine import WorkflowEngine
    engine = WorkflowEngine(db)

    attention_items = engine.get_needs_attention()
    tickets = engine.get_all_tickets()
    approval_queue = engine.get_approval_queue()
    paper_queue = engine.get_paper_trading_queue()
    retirement_queue = engine.get_retirement_queue()

    # Top metrics
    # Top metrics
    m1, m2, m3, m4, m5, m6 = st.columns(6)
    m1.metric("Total hypotheses", len(tickets))
    m2.metric("Pending approval", len(approval_queue))
    m3.metric("Paper trading", len(paper_queue))
    m4.metric("Decay flagged", sum(1 for t in tickets if t.decay_flag))
    m5.metric("Compliance warnings",
              sum(1 for t in tickets if t.compliance_warning))

    # Scheduler button
    if m6.button("⚙️ Run Scheduler", type="secondary", key="run_scheduler"):
        from src.agents.research_scheduler import run_scheduler
        with st.spinner("Running research scheduler..."):
            schedule_result = run_scheduler(db)
        st.session_state["last_schedule"] = schedule_result
        st.rerun()

    # Trigger consumer
    pending_triggers = db.execute(text(
        "SELECT COUNT(*) FROM research_triggers WHERE status = 'pending'"
    )).scalar()

    if pending_triggers and pending_triggers > 0:
        st.warning(f"⚡ {pending_triggers} Portfolio Lab research trigger(s) pending")
        if st.button(f"🔬 Run triggered research ({pending_triggers})",
                    type="primary", key="run_triggers"):
            st.info("Run this command to consume triggers:")
            st.code("python -m src.pipeline.research_cycle --consume-triggers")

    if "last_schedule" in st.session_state:
        sr = st.session_state["last_schedule"]
        with st.expander(f"Last scheduler run — {sr['total_decided']} decisions"):
            st.caption(sr["summary"])
            for d in sr["decisions"]:
                icon = {"RUN": "🟢", "DELAY": "🟡",
                        "CANCEL": "🔴", "MERGE": "🔵"}.get(d["action"], "⚪")
                st.markdown(f"{icon} **H#{d['hypothesis_number']}** → {d['action']} "
                           f"(score {d['priority_score']:.2f}) — {d['reasoning'][:80]}")

    st.divider()

    # Needs attention
    if attention_items:
        st.markdown("### ⚡ Needs attention")
        for item in attention_items:
            color = "error" if item["priority"] == "high" else "warning"
            getattr(st, color)(
                f"**{item['type'].replace('_', ' ').title()}** — "
                f"{item['message']} "
                f"(H#{', #'.join(str(n) for n in item['tickets'])})"
            )
    else:
        st.success("No items need immediate attention.")

    st.divider()
    col1, col2 = st.columns(2)

    with col1:
        st.markdown("### Approval queue")
        if approval_queue:
            for t in approval_queue[:5]:
                with st.container(border=True):
                    c1, c2 = st.columns([3, 1])
                    c1.markdown(f"**H#{t.number}** — {t.title[:45]}")
                    c2.markdown(f"`{t.stage.value}`")
                    st.caption(f"Next: {t.next_action} | {t.days_in_stage}d in stage")
                    if t.compliance_warning:
                        st.caption("⚠️ Has compliance warning")
        else:
            st.info("Nothing pending approval.")

    with col2:
        st.markdown("### Paper trading")
        if paper_queue:
            for t in paper_queue[:5]:
                with st.container(border=True):
                    decay_icon = "⚠️" if t.decay_flag else "✅"
                    st.markdown(f"{decay_icon} **H#{t.number}** — {t.title[:45]}")
                    if t.hypothesis.sharpe_ratio:
                        st.caption(f"Sharpe {t.hypothesis.sharpe_ratio:.3f} | "
                                  f"MaxDD {t.hypothesis.max_drawdown:.1%}")
        else:
            st.info("No hypotheses in paper trading.")

elif page == "📋 Experiment Board":
    st.title("Experiment board")
    st.caption("All hypotheses as research tickets, grouped by governance stage.")

    from src.agents.workflow_engine import WorkflowEngine
    engine = WorkflowEngine(db)
    board = engine.get_experiment_board()

    STAGE_ORDER = ["idea", "experiment", "statistical_review", "risk_review",
                   "committee", "paper_trading", "production", "monitoring", "retired"]
    STAGE_COLORS = {
        "idea": "🔵", "experiment": "🟡", "statistical_review": "🟠",
        "risk_review": "🟠", "committee": "🔴", "paper_trading": "🟢",
        "production": "✅", "monitoring": "✅", "retired": "⚫"
    }

    for stage in STAGE_ORDER:
        tickets = board.get(stage, [])
        if not tickets:
            continue
        icon = STAGE_COLORS.get(stage, "⚪")
        st.markdown(f"### {icon} {stage.replace('_', ' ').title()} ({len(tickets)})")
        cols = st.columns(min(len(tickets), 3))
        for i, t in enumerate(tickets):
            with cols[i % 3]:
                with st.container(border=True):
                    warn = "⚠️ " if t.compliance_warning else ""
                    st.markdown(f"**{warn}H#{t.number}**")
                    st.caption(t.title[:50])
                    if t.has_backtest:
                        st.caption(f"Sharpe {t.hypothesis.sharpe_ratio:.3f}")
                    st.caption(f"Next: {t.next_action}")
                    st.caption(f"{t.days_in_stage}d in stage")

elif page == "⏳ Approval Queue":
    st.title("Approval queue")
    st.caption("Hypotheses waiting for the next pipeline step — oldest first.")

    from src.agents.workflow_engine import WorkflowEngine
    engine = WorkflowEngine(db)
    queue = engine.get_approval_queue()

    if not queue:
        st.success("Approval queue is empty.")
    else:
        for t in queue:
            with st.container(border=True):
                c1, c2, c3 = st.columns([3, 1, 1])
                c1.markdown(f"**H#{t.number} — {t.title}**")
                c2.markdown(f"`{t.stage.value}`")
                c3.markdown(f"**{t.days_in_stage}d**")

                st.caption(f"🔧 Next action: **{t.next_action}** (actor: {t.actor})")
                if t.command:
                    st.code(t.command, language="bash")
                if t.compliance_warning:
                    st.warning("This hypothesis has unresolved compliance warnings — "
                              "review governance timeline before proceeding.")

elif page == "📈 Paper Trading Queue":
    st.title("Paper trading queue")
    st.caption("Approved alphas currently in paper trading — monitor for decay.")

    from src.agents.workflow_engine import WorkflowEngine
    from sqlalchemy import text as sqla_text
    engine = WorkflowEngine(db)
    queue = engine.get_paper_trading_queue()

    if not queue:
        st.info("No hypotheses in paper trading.")
    else:
        for t in queue:
            with st.container(border=True):
                decay_icon = "⚠️ DECAY" if t.decay_flag else "✅ Active"
                st.markdown(f"**H#{t.number} — {t.title}** — {decay_icon}")

                m1, m2, m3 = st.columns(3)
                m1.metric("Backtest Sharpe",
                          f"{t.hypothesis.sharpe_ratio:.3f}"
                          if t.hypothesis.sharpe_ratio else "—")
                m2.metric("Max DD",
                          f"{t.hypothesis.max_drawdown:.1%}"
                          if t.hypothesis.max_drawdown else "—")
                m3.metric("Days in paper trading", t.days_in_stage)

                # Latest learning report
                lr = db.execute(sqla_text(
                    "SELECT paper_sharpe, recommended_action, evaluated_at "
                    "FROM learning_reports WHERE hypothesis_id = :hid "
                    "ORDER BY evaluated_at DESC LIMIT 1"
                ), {"hid": str(t.hypothesis.id)}).fetchone()

                if lr:
                    st.caption(
                        f"Latest eval: Paper Sharpe {lr.paper_sharpe:.3f} | "
                        f"Action: {lr.recommended_action} | "
                        f"Date: {str(lr.evaluated_at)[:10]}"
                    )

elif page == "🗄️ Retirement Queue":
    st.title("Retirement queue")
    st.caption("Signals flagged for decay or stuck in revision — review for retirement.")

    from src.agents.workflow_engine import WorkflowEngine
    engine = WorkflowEngine(db)
    queue = engine.get_retirement_queue()

    if not queue:
        st.success("No signals flagged for retirement.")
    else:
        for t in queue:
            with st.container(border=True):
                reason = "Decay flagged" if t.decay_flag else "Revision requested >7 days"
                st.markdown(f"**H#{t.number} — {t.title}**")
                st.caption(f"Reason: {reason} | Stage: {t.stage.value} | "
                          f"{t.days_in_stage}d in stage")

                from src.agents.governance_actions import retire_hypothesis
                from src.models.governance import GovernanceStage
                retire_key = f"retire_queue_{t.number}"
                notes_key = f"retire_notes_{t.number}"
                notes = st.text_input("Retirement reason", key=notes_key,
                                     placeholder="Document reason for retirement...")
                if st.button(f"🗄️ Retire H#{t.number}", key=retire_key, type="secondary"):
                    if notes:
                        ok, msg = retire_hypothesis(db, t.hypothesis, notes)
                        if ok:
                            st.success(msg)
                            st.rerun()
                        else:
                            st.error(msg)
                    else:
                        st.error("Retirement reason is required.")

# ── Page: Macro Data ──────────────────────────────────────────────
elif page == "Macro Data":
    st.title("Macro data")
    st.caption("Real-time macro regime from FRED — feeds directly into Research Scientist observations.")

    from src.data.fred_client import get_macro_snapshot, macro_snapshot_to_observations

    if st.button("Refresh FRED data", type="primary", key="fred_refresh"):
        with st.spinner("Fetching from FRED..."):
            st.session_state["fred_snapshot"] = get_macro_snapshot()

    if "fred_snapshot" not in st.session_state:
        with st.spinner("Fetching from FRED..."):
            st.session_state["fred_snapshot"] = get_macro_snapshot()

    snapshot = st.session_state["fred_snapshot"]

    if "error" in snapshot:
        st.error(f"FRED unavailable: {snapshot['error']}")
    else:
        st.caption(f"Last updated: {snapshot['timestamp']}")

        # Regime badges
        r1, r2, r3, r4, r5 = st.columns(5)
        regime_colors = {
            "expansion": "🟢", "transition": "🟡",
            "contraction": "🔴", "late_cycle": "🟠", "unknown": "⚪"
        }
        vix_colors = {"low": "🟢", "elevated": "🟡", "stressed": "🔴", "unknown": "⚪"}
        inflation_colors = {"low": "🟢", "moderate": "🟡", "high": "🔴",
                           "deflating": "🔵", "unknown": "⚪"}
        curve_colors = {"normal": "🟢", "flat": "🟡", "inverted": "🔴", "unknown": "⚪"}
        rate_colors = {"stable": "🟢", "falling": "🟡", "rising": "🔴", "unknown": "⚪"}

        r1.metric("Regime",
                  f"{regime_colors.get(snapshot['regime'], '⚪')} {snapshot['regime']}")
        r2.metric("VIX",
                  f"{vix_colors.get(snapshot['vix_regime'], '⚪')} {snapshot['vix_regime']}")
        r3.metric("Inflation",
                  f"{inflation_colors.get(snapshot['inflation_pressure'], '⚪')} "
                  f"{snapshot['inflation_pressure']}")
        r4.metric("Yield Curve",
                  f"{curve_colors.get(snapshot['yield_curve'], '⚪')} {snapshot['yield_curve']}")
        r5.metric("Rates",
                  f"{rate_colors.get(snapshot['rate_environment'], '⚪')} "
                  f"{snapshot['rate_environment']}")

        st.divider()

        # Key levels
        st.markdown("### Key levels")
        kl = snapshot["key_levels"]
        c1, c2, c3 = st.columns(3)
        with c1:
            if kl.get("fed_funds_rate"):
                st.metric("Fed Funds Rate", f"{kl['fed_funds_rate']:.2f}%")
            if kl.get("unemployment_rate"):
                st.metric("Unemployment", f"{kl['unemployment_rate']:.1f}%")
            if kl.get("cpi_yoy_pct"):
                st.metric("CPI YoY", f"{kl['cpi_yoy_pct']:.2f}%",
                         delta="above target" if kl['cpi_yoy_pct'] > 2.5 else "near target",
                         delta_color="inverse")
        with c2:
            if kl.get("ten_year_yield"):
                st.metric("10Y Treasury", f"{kl['ten_year_yield']:.2f}%")
            if kl.get("yield_spread_10y2y"):
                st.metric("10Y-2Y Spread", f"{kl['yield_spread_10y2y']:.2f}%",
                         delta="normal" if kl['yield_spread_10y2y'] > 0.5
                         else "flat" if kl['yield_spread_10y2y'] > 0
                         else "inverted",
                         delta_color="normal" if kl['yield_spread_10y2y'] > 0.5
                         else "off")
        with c3:
            if kl.get("vix"):
                st.metric("VIX", f"{kl['vix']:.1f}",
                         delta="above strategy threshold (15)"
                         if kl['vix'] > 15 else "within strategy range",
                         delta_color="inverse" if kl['vix'] > 15 else "normal")
            if kl.get("oil_price"):
                st.metric("WTI Crude", f"${kl['oil_price']:.1f}/bbl")

        st.divider()
        st.markdown("### Research Scientist observations")
        st.caption("These values are passed directly to the Research Scientist when running the pipeline.")
        obs = macro_snapshot_to_observations(snapshot)
        for k, v in obs.items():
            st.markdown(f"**{k}**: {v}")

        # Strategy implication
        st.divider()
        st.markdown("### Strategy implications")
        vix = kl.get("vix", 0)
        cpi = kl.get("cpi_yoy_pct", 0)
        spread = kl.get("yield_spread_10y2y", 0)

        implications = []
        if vix and vix > 15:
            implications.append(
                f"⚠️ VIX {vix:.1f} is above the <15 entry threshold used by "
                f"most registered alphas — momentum strategies currently outside "
                f"their optimal deployment window"
            )
        if cpi and cpi > 4:
            implications.append(
                f"⚠️ CPI YoY {cpi:.1f}% is elevated — earnings revision signals "
                f"may be distorted by nominal growth; consider real earnings adjustments"
            )
        if spread is not None and 0 < spread < 0.5:
            implications.append(
                f"⚠️ Yield curve flat ({spread:.2f}%) — historically precedes "
                f"late-cycle slowdown; momentum strategies show reduced persistence "
                f"in flat-curve environments"
            )
        if not implications:
            implications.append("✅ Macro conditions broadly supportive of deployed strategies")

        for imp in implications:
            st.markdown(f"- {imp}")

        # Economic calendar
        st.divider()
        st.markdown("### Economic calendar (next 30 days)")
        try:
            from src.data.fred_client import get_upcoming_releases, calendar_to_risk_context
            with st.spinner("Loading calendar..."):
                cal_events = get_upcoming_releases(days_ahead=30)
            ctx = calendar_to_risk_context(cal_events)

            risk_colors = {
                "low": "✅", "moderate": "🟡",
                "elevated": "🟠", "critical": "🔴"
            }
            st.markdown(
                f"{risk_colors.get(ctx['near_term_risk'], '⚪')} "
                f"**Near-term risk: {ctx['near_term_risk'].upper()}** — "
                f"{ctx['summary']}"
            )

            if cal_events:
                import pandas as pd
                cal_df = pd.DataFrame([{
                    "Date": e["date"],
                    "Days": e["days_until"],
                    "Event": e["name"],
                    "Importance": e["importance"],
                    "Signal": e["signal"],
                    "VIX Impact": e["typical_vix_impact"]
                } for e in cal_events])
                st.dataframe(cal_df, use_container_width=True, hide_index=True)
            else:
                st.info("No major events in the next 30 days.")
        except Exception as e:
            st.warning(f"Calendar unavailable: {e}")


db.close()